version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: npm
    directory: /src/Dome.Client
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/Dome.Server/Dome.Api
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/Dome.Socket/Dome.Socket.Api
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/Dome.Client
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  
