version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: npm
    directory: /src/HomelabDocs.Client
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/HomelabDocs.Server/HomelabDocs.Api
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/HomelabDocs.Socket/HomelabDocs.Socket.Api
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  

  - package-ecosystem: docker
    directory: /src/HomelabDocs.Client
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      monthly-batch:
        patterns:
          - "*"  
