version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/HomelabDocs.Server
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /src/HomelabDocs.Client
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/HomelabDocs.Server/HomelabDocs.Api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/HomelabDocs.Client
    schedule:
      interval: weekly
    
