// <auto-generated />
using HomelabDocs.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace HomelabDocs.Domain.Migrations
{
    [DbContext(typeof(HomelabDocsDbContext))]
    partial class HomelabDocsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
        }
    }
}
