<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Swagger" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomelabDocs.Business\HomelabDocs.Business.csproj" />
    <ProjectReference Include="..\HomelabDocs.Domain\HomelabDocs.Domain.csproj" />
    <ProjectReference Include="..\HomelabDocs.Shared\HomelabDocs.Shared.csproj" />
  </ItemGroup>

</Project>
