<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Refit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomelabDocs.Domain\HomelabDocs.Domain.csproj" />
    <ProjectReference Include="..\HomelabDocs.Shared\HomelabDocs.Shared.csproj" />
    <ProjectReference Include="..\..\HomelabDocs.Socket\HomelabDocs.Socket.Contracts\HomelabDocs.Socket.Contracts.csproj" />
  </ItemGroup>

</Project>
